// Cloudflare Worker — files.moviesss4ers.workers.dev
//
// Routes:
// /watch/, /stream/, /dl/  → proxy to Koyeb stream server
// ?link=XXX                → show beautiful landing page with GET FILE button
//                            clicking GET FILE opens Telegram → ServeBot → sends file

const KOYEB_URL = "https://marvellous-ilse-dengerous53-077d6f54.koyeb.app";

// Cache serve bot username — refreshes every 5 minutes
let cachedServeBotUsername = null;
let cacheTime = 0;
const CACHE_TTL = 5 * 60 * 1000;


// ── Fetch helpers ──────────────────────────────────────────────────────────────

async function getServeBotUsername() {
  const now = Date.now();
    if (cachedServeBotUsername && (now - cacheTime) < CACHE_TTL) {
        return cachedServeBotUsername;
          }
            try {
                const resp = await fetch(`${KOYEB_URL}/serve_bot`);
                    const data = await resp.json();
                        cachedServeBotUsername = data.username;
                            cacheTime = now;
                                return cachedServeBotUsername;
                                  } catch (err) {
                                      return cachedServeBotUsername || "";
                                        }
                                        }


                                        // ── Landing page HTML ──────────────────────────────────────────────────────────

                                        function buildLandingPage(telegramUrl) {
                                          return `<!DOCTYPE html>
                                          <html lang="en">
                                          <head>
                                          <meta charset="UTF-8">
                                          <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                          <title>Moviesss4ers Files</title>
                                          <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
                                          <style>
                                            :root {
                                                --bg:#080a0f; --surface:#0e1118; --border:rgba(255,255,255,0.06);
                                                    --accent:#e63946; --accent2:#ff6b6b; --text:#f0f0f0;
                                                        --muted:#6b7280; --glow:rgba(230,57,70,0.35);
                                                          }
                                                            * { margin:0; padding:0; box-sizing:border-box; }
                                                              html, body { height:100%; }
                                                                body {
                                                                    background:var(--bg); color:var(--text);
                                                                        font-family:'DM Sans',sans-serif;
                                                                            min-height:100vh; display:flex; flex-direction:column;
                                                                                align-items:center; justify-content:center;
                                                                                    padding:24px 16px; overflow-x:hidden;
                                                                                      }
                                                                                        body::before {
                                                                                            content:''; position:fixed; inset:0;
                                                                                                background:
                                                                                                      radial-gradient(ellipse 80% 50% at 50% -10%,rgba(230,57,70,0.14) 0%,transparent 60%),
                                                                                                            radial-gradient(ellipse 50% 40% at 80% 90%,rgba(230,57,70,0.07) 0%,transparent 50%);
                                                                                                                pointer-events:none; z-index:0;
                                                                                                                  }
                                                                                                                    .container {
                                                                                                                        position:relative; z-index:1; width:100%; max-width:460px;
                                                                                                                            display:flex; flex-direction:column; align-items:center; text-align:center;
                                                                                                                              }
                                                                                                                                .brand {
                                                                                                                                    display:flex; flex-direction:column; align-items:center; gap:10px;
                                                                                                                                        margin-bottom:32px; animation:fadeDown 0.6s ease both;
                                                                                                                                          }
                                                                                                                                            .logo-mark {
                                                                                                                                                width:62px; height:62px; background:var(--accent); border-radius:18px;
                                                                                                                                                    display:flex; align-items:center; justify-content:center;
                                                                                                                                                        box-shadow:0 0 40px var(--glow);
                                                                                                                                                          }
                                                                                                                                                            .logo-mark svg { width:30px; height:30px; fill:white; }
                                                                                                                                                              .brand-name {
                                                                                                                                                                  font-family:'Bebas Neue',sans-serif; font-size:28px;
                                                                                                                                                                      letter-spacing:3px; color:var(--text);
                                                                                                                                                                        }
                                                                                                                                                                          .brand-handle { font-size:13px; color:var(--accent2); font-weight:500; }
                                                                                                                                                                            .card {
                                                                                                                                                                                width:100%; background:var(--surface); border:1px solid var(--border);
                                                                                                                                                                                    border-radius:20px; padding:40px 28px 36px;
                                                                                                                                                                                        display:flex; flex-direction:column; align-items:center; gap:26px;
                                                                                                                                                                                            box-shadow:0 20px 60px rgba(0,0,0,0.4);
                                                                                                                                                                                                animation:fadeUp 0.7s ease 0.15s both; position:relative; overflow:hidden;
                                                                                                                                                                                                  }
                                                                                                                                                                                                    .card::before {
                                                                                                                                                                                                        content:''; position:absolute; top:0; left:0; right:0; height:2px;
                                                                                                                                                                                                            background:linear-gradient(90deg,transparent,var(--accent),transparent);
                                                                                                                                                                                                              }
                                                                                                                                                                                                                .file-icon {
                                                                                                                                                                                                                    width:74px; height:74px; background:rgba(230,57,70,0.1);
                                                                                                                                                                                                                        border:1px solid rgba(230,57,70,0.2); border-radius:20px;
                                                                                                                                                                                                                            display:flex; align-items:center; justify-content:center;
                                                                                                                                                                                                                                animation:pulseGlow 2s ease infinite;
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                    .file-icon svg { width:34px; height:34px; fill:none; stroke:var(--accent2); stroke-width:1.5; }
                                                                                                                                                                                                                                      .card-title {
                                                                                                                                                                                                                                          font-family:'Bebas Neue',sans-serif; font-size:38px;
                                                                                                                                                                                                                                              letter-spacing:2px; line-height:1; color:var(--text);
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  .card-sub { font-size:14px; color:var(--muted); line-height:1.6; margin-top:-12px; }
                                                                                                                                                                                                                                                    .get-btn {
                                                                                                                                                                                                                                                        display:inline-flex; align-items:center; justify-content:center; gap:10px;
                                                                                                                                                                                                                                                            width:100%; max-width:280px; padding:18px 32px;
                                                                                                                                                                                                                                                                background:var(--accent); color:white; text-decoration:none;
                                                                                                                                                                                                                                                                    border-radius:14px; font-family:'Bebas Neue',sans-serif;
                                                                                                                                                                                                                                                                        font-size:24px; letter-spacing:2.5px;
                                                                                                                                                                                                                                                                            box-shadow:0 8px 36px var(--glow); transition:all 0.2s ease;
                                                                                                                                                                                                                                                                                position:relative; overflow:hidden;
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                    .get-btn::after {
                                                                                                                                                                                                                                                                                        content:''; position:absolute; inset:0;
                                                                                                                                                                                                                                                                                            background:linear-gradient(135deg,rgba(255,255,255,0.1) 0%,transparent 60%);
                                                                                                                                                                                                                                                                                                pointer-events:none;
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                    .get-btn:hover { background:var(--accent2); transform:translateY(-3px); box-shadow:0 14px 44px var(--glow); }
                                                                                                                                                                                                                                                                                                      .get-btn:active { transform:translateY(-1px); }
                                                                                                                                                                                                                                                                                                        .get-btn svg { width:20px; height:20px; fill:none; stroke:white; stroke-width:2.5; }
                                                                                                                                                                                                                                                                                                          .tg-hint {
                                                                                                                                                                                                                                                                                                              display:flex; align-items:center; gap:6px;
                                                                                                                                                                                                                                                                                                                  font-size:12px; color:var(--muted);
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                      .tg-hint svg { width:14px; height:14px; fill:var(--muted); }
                                                                                                                                                                                                                                                                                                                        .channel-btn {
                                                                                                                                                                                                                                                                                                                            display:inline-flex; align-items:center; gap:8px;
                                                                                                                                                                                                                                                                                                                                padding:10px 22px; background:rgba(255,255,255,0.04);
                                                                                                                                                                                                                                                                                                                                    border:1px solid var(--border); border-radius:30px;
                                                                                                                                                                                                                                                                                                                                        color:var(--text); text-decoration:none; font-size:13px; font-weight:500;
                                                                                                                                                                                                                                                                                                                                            transition:all 0.2s ease; margin-top:22px;
                                                                                                                                                                                                                                                                                                                                                animation:fadeUp 0.7s ease 0.3s both;
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                    .channel-btn:hover { background:rgba(255,255,255,0.08); border-color:rgba(255,255,255,0.12); }
                                                                                                                                                                                                                                                                                                                                                      .channel-btn svg { width:15px; height:15px; fill:var(--accent2); }
                                                                                                                                                                                                                                                                                                                                                        @keyframes fadeDown { from{opacity:0;transform:translateY(-20px)} to{opacity:1;transform:translateY(0)} }
                                                                                                                                                                                                                                                                                                                                                          @keyframes fadeUp   { from{opacity:0;transform:translateY(24px)}  to{opacity:1;transform:translateY(0)} }
                                                                                                                                                                                                                                                                                                                                                            @keyframes pulseGlow {
                                                                                                                                                                                                                                                                                                                                                                0%,100%{box-shadow:0 0 0 0 rgba(230,57,70,0.0)}
                                                                                                                                                                                                                                                                                                                                                                    50%{box-shadow:0 0 22px 4px rgba(230,57,70,0.2)}
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                        @media(max-width:400px) {
                                                                                                                                                                                                                                                                                                                                                                            .card{padding:32px 18px 28px}
                                                                                                                                                                                                                                                                                                                                                                                .card-title{font-size:30px}
                                                                                                                                                                                                                                                                                                                                                                                    .get-btn{font-size:20px;padding:16px 24px}
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                      </style>
                                                                                                                                                                                                                                                                                                                                                                                      </head>
                                                                                                                                                                                                                                                                                                                                                                                      <body>
                                                                                                                                                                                                                                                                                                                                                                                      <div class="container">

                                                                                                                                                                                                                                                                                                                                                                                        <div class="brand">
                                                                                                                                                                                                                                                                                                                                                                                            <div class="logo-mark">
                                                                                                                                                                                                                                                                                                                                                                                                  <svg viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M17 8l-5-5-5 5M12 3v12"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                          <div class="brand-name">Moviesss4ers Files</div>
                                                                                                                                                                                                                                                                                                                                                                                                              <div class="brand-handle">@Moviesss4ers</div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="card">

                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="file-icon">
                                                                                                                                                                                                                                                                                                                                                                                                                            <svg viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <polyline points="14 2 14 8 20 8"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <line x1="16" y1="13" x2="8" y2="13"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <line x1="16" y1="17" x2="8" y2="17"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-title">Your File is Ready</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="${telegramUrl}" class="get-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <svg viewBox="0 0 24 24"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          GET FILE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="tg-hint">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <svg viewBox="0 0 24 24"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07A19.5 19.5 0 013.07 9.8 19.79 19.79 0 01.22 1.18 2 2 0 012.18 0h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L6.91 7.91a16 16 0 006.72 6.72l1.06-1.06a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Opens in Telegram
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="https://t.me/Moviesss4ers" class="channel-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <svg viewBox="0 0 24 24"><path d="M22 2L11 13M22 2L15 22l-4-9-9-4 20-7z"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Join @Moviesss4ers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ── Main handler ───────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addEventListener('fetch', event => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  event.respondWith(handleRequest(event.request));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async function handleRequest(request) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const url = new URL(request.url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const pathname = url.pathname;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ── Stream/Download proxy routes ──────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const streamRoutes = ["/watch/", "/stream/", "/dl/"];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const isStreamRoute = streamRoutes.some(path => pathname.startsWith(path));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (isStreamRoute) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const targetUrl = KOYEB_URL + pathname + url.search;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const forwardHeaders = new Headers(request.headers);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          forwardHeaders.set("Host", new URL(KOYEB_URL).host);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const koyebResponse = await fetch(targetUrl, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            method: request.method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: forwardHeaders,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            body: request.method !== "GET" && request.method !== "HEAD" ? request.body : undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    redirect: "follow",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const responseHeaders = new Headers(koyebResponse.headers);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      responseHeaders.delete("transfer-encoding");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            responseHeaders.delete("connection");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  responseHeaders.set("Access-Control-Allow-Origin", "*");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        responseHeaders.set("Access-Control-Allow-Headers", "Range, Content-Type");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              responseHeaders.set("Access-Control-Expose-Headers", "Content-Range, Content-Length, Accept-Ranges");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(koyebResponse.body, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status: koyebResponse.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    statusText: koyebResponse.statusText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: responseHeaders,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Response("Gateway error: " + err.message, { status: 502 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ── File link — show landing page ─────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const linkParam = url.searchParams.get("link");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (linkParam) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const serveBotUsername = await getServeBotUsername();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!serveBotUsername) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return new Response("Service unavailable — serve bot not configured.", { status: 503 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Build Telegram deep link → opens ServeBot → serves file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const telegramUrl = `https://t.me/${serveBotUsername}?start=${linkParam}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Show landing page — user clicks GET FILE to open Telegram
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const html = buildLandingPage(telegramUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(html, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Content-Type": "text/html;charset=UTF-8",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Cache-Control": "no-cache"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ── Unknown route — redirect to channel ───────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return Response.redirect("https://t.me/Moviesss4ers", 302);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
