# Multi-Language Support (i18n)
# Supported: en, hi, es, fr, ar, pt, id, tr

LANGUAGES = {
    "en": {
        "lang_name": "English 🇬🇧",
        "start_msg": "Hello, [{name}](tg://user?id={id})\n\nThis is a Literally Permanent **FileStore Bot**.\n\nHow to Use Bot & it's Benefits??\n\n📢 Send me any File & It will be uploaded in My Database & You will Get the File Link Which Never Expires.\n\n⚠️ **Benefits**: If you have a TeleGram Movie Channel or Any Copyright Channel, Then Its Useful for Daily Usage, You can Send Me Your File & I will Send Permanent Link to You & Channel will be Safe from **CopyRight Infringement** Issue.\n\n🗣️ **For Example**: If Bot Get Banned & Deleted, Your All Links will Redirect to New Bot & All Files Are Still Accessable, Dont Worry You Don't have to Make any Changes Anywhere Because We Do 😎\n\n❌ **PORNOGRAPHY CONTENTS** are strictly prohibited & get Permanent Ban.",
        "about_bot": "ℹ️ I am a Permanent File Store Bot built with Pyrogram.",
        "force_sub": "**Please Join the Update Channel(s) to use this Bot!**\n\nDue to overload, only channel subscribers can use this Bot!",
        "join_button": "🤖 Join Channel",
        "refresh_button": "🔄 Refresh 🔄",
        "banned_msg": "Sorry, you are banned!",
        "file_deleted": "✅ File was auto-deleted to prevent copyright.\n\n©️ <b>Powered by @Moviesss4ers 🏆.</b>",
        "auto_delete_warn": "⚠️ <b>Due To Copyright This file will deleted after <u>{time}</u>.</b>\n\n📌 Please save/forward it before download!",
        "save_batch": "Save in Batch",
        "get_link": "Get Sharable Link",
        "choose_option": "**Choose an option from below:**",
        "file_stored": "**Your File Stored in Database ✅**\n\nHere is the Permanent Link of your file: {link}\n\nClick **Open Link** to get your file!",
        "batch_stored": "**Batch Files Stored in Database ✅**\n\nHere is the Permanent Link of your files: {link}\n\nClick **Open Link** to get your files!",
        "batch_added": "File Saved in Batch! ({count}/20)\n\nPress below button to get batch link.",
        "batch_limit": "⚠️ **Batch Limit Reached!**\n\nYou can only add up to **20 files** in one batch.\n\nUse /clear_batch to start a new batch.",
        "get_batch_link": "Get Batch Link",
        "open_link": "Open Link",
        "close_msg": "Close Message",
        "error_msg": "Something went wrong!\n\n**Error:** `{err}`",
        "token_expired": "⏰ **Your token has expired!**\n\nPlease verify again to access files.",
        "token_verify": "🔐 **Verification Required**\n\nClick the button below to verify yourself. Token is valid for {time}.",
        "verify_button": "✅ Verify Now",
        "token_verified": "✅ **Token Verified Successfully!**\n\nYou can now access files for the next {time}.",
        "clone_success": "✅ **Bot Cloned Successfully!**\n\nYour clone bot @{username} is now active.\n\nUse /removeclone to remove it.",
        "clone_usage": "**Usage:** `/clone BOT_TOKEN DB_CHANNEL_ID`\n\nExample: `/clone 123456:ABC -1001234567890`",
        "clone_removed": "✅ Clone bot removed successfully!",
        "admin_added": "✅ User `{user_id}` added as admin.",
        "admin_removed": "✅ User `{user_id}` removed from admin.",
        "admin_list": "📋 **Admin List:**\n\n{admins}",
        "not_admin": "❌ You are not authorized to use this command!",
        "language_changed": "✅ Language changed to **{lang}**!",
        "choose_lang": "🌐 **Choose your preferred language:**",
        "protect_content_on": "🔒 Content protection is **enabled**.",
        "stream_link": "🔗 **Stream/Download Link:**\n\n{link}",
        "our_channel": "Our Channel",
        "our_group": "Our Group",
        "about_bot_btn": "About Bot",
        "about_dev_btn": "About Dev",
        "close_btn": "Close 🚪",
        "go_home": "Go Home",
    },

    "hi": {
        "lang_name": "हिंदी 🇮🇳",
        "start_msg": "नमस्ते, [{name}](tg://user?id={id})\n\nयह एक स्थायी **फाइल स्टोर बॉट** है।\n\n📢 मुझे कोई भी फाइल भेजें और मैं उसे स्टोर करके स्थायी लिंक दूंगा।",
        "about_bot": "ℹ️ मैं Pyrogram से बना एक स्थायी फाइल स्टोर बॉट हूं।",
        "force_sub": "**बॉट उपयोग करने के लिए कृपया अपडेट चैनल(लों) से जुड़ें!**\n\nअधिक लोड के कारण, केवल चैनल सदस्य ही इस बॉट का उपयोग कर सकते हैं!",
        "join_button": "🤖 चैनल जॉइन करें",
        "refresh_button": "🔄 रिफ्रेश 🔄",
        "banned_msg": "क्षमा करें, आप प्रतिबंधित हैं!",
        "file_deleted": "✅ कॉपीराइट समस्याओं से बचने के लिए फाइल ऑटो-डिलीट कर दी गई।\n\n🔁 दोबारा डाउनलोड करने के लिए लिंक पर क्लिक करें।",
        "auto_delete_warn": "⚠️ <b>यह फाइल <u>{time}</u> में ऑटो-डिलीट हो जाएगी।</b>\n\n📌 कृपया डिलीट होने से पहले सेव/फॉरवर्ड करें!",
        "save_batch": "बैच में सेव करें",
        "get_link": "शेयर लिंक प्राप्त करें",
        "choose_option": "**नीचे से एक विकल्प चुनें:**",
        "file_stored": "**आपकी फाइल डेटाबेस में स्टोर हो गई ✅**\n\nआपकी फाइल का स्थायी लिंक: {link}\n\n**Open Link** पर क्लिक करें!",
        "batch_stored": "**बैच फाइलें डेटाबेस में स्टोर हो गईं ✅**\n\nआपकी फाइलों का स्थायी लिंक: {link}\n\n**Open Link** पर क्लिक करें!",
        "batch_added": "फाइल बैच में सेव हो गई! ({count}/20)\n\nबैच लिंक प्राप्त करने के लिए नीचे बटन दबाएं।",
        "batch_limit": "⚠️ **बैच सीमा पहुँच गई!**\n\nआप एक बैच में अधिकतम **20 फाइलें** ही जोड़ सकते हैं।\n\nनया बैच शुरू करने के लिए /clear_batch उपयोग करें।",
        "get_batch_link": "बैच लिंक प्राप्त करें",
        "open_link": "लिंक खोलें",
        "close_msg": "बंद करें",
        "error_msg": "कुछ गलत हो गया!\n\n**त्रुटि:** `{err}`",
        "token_expired": "⏰ **आपका टोकन समाप्त हो गया है!**\n\nफाइलें एक्सेस करने के लिए फिर से वेरीफाई करें।",
        "token_verify": "🔐 **वेरिफिकेशन आवश्यक**\n\nवेरीफाई करने के लिए नीचे बटन पर क्लिक करें। टोकन {time} के लिए वैध है।",
        "verify_button": "✅ अभी वेरीफाई करें",
        "token_verified": "✅ **टोकन सफलतापूर्वक वेरीफाई हो गया!**\n\nअब आप अगले {time} तक फाइलें एक्सेस कर सकते हैं।",
        "clone_success": "✅ **बॉट सफलतापूर्वक क्लोन हो गया!**\n\nआपका क्लोन बॉट @{username} अब सक्रिय है।\n\nहटाने के लिए /removeclone उपयोग करें।",
        "clone_usage": "**उपयोग:** `/clone BOT_TOKEN DB_CHANNEL_ID`\n\nउदाहरण: `/clone 123456:ABC -1001234567890`",
        "clone_removed": "✅ क्लोन बॉट सफलतापूर्वक हटा दिया गया!",
        "admin_added": "✅ उपयोगकर्ता `{user_id}` को एडमिन बनाया गया।",
        "admin_removed": "✅ उपयोगकर्ता `{user_id}` को एडमिन से हटाया गया।",
        "admin_list": "📋 **एडमिन सूची:**\n\n{admins}",
        "not_admin": "❌ आप इस कमांड का उपयोग करने के लिए अधिकृत नहीं हैं!",
        "language_changed": "✅ भाषा **{lang}** में बदल गई!",
        "choose_lang": "🌐 **अपनी पसंदीदा भाषा चुनें:**",
        "protect_content_on": "🔒 कंटेंट प्रोटेक्शन **सक्षम** है।",
        "stream_link": "🔗 **स्ट्रीम/डाउनलोड लिंक:**\n\n{link}",
        "our_channel": "हमारा चैनल",
        "our_group": "हमारा ग्रुप",
        "about_bot_btn": "बॉट के बारे में",
        "about_dev_btn": "डेवलपर के बारे में",
        "close_btn": "बंद करें 🚪",
        "go_home": "होम जाएं",
    },

    "es": {
        "lang_name": "Español 🇪🇸",
        "start_msg": "Hola, [{name}](tg://user?id={id})\n\nEste es un Bot de **Almacén de Archivos** permanente.\n\n📢 Envíame cualquier archivo y te daré un enlace permanente.",
        "about_bot": "ℹ️ Soy un bot de almacenamiento de archivos permanente construido con Pyrogram.",
        "force_sub": "**¡Por favor únete a los canales de actualización para usar este bot!**\n\n¡Solo los suscriptores del canal pueden usar este bot!",
        "join_button": "🤖 Unirse al Canal",
        "refresh_button": "🔄 Actualizar 🔄",
        "banned_msg": "¡Lo siento, estás baneado!",
        "file_deleted": "✅ El archivo fue auto-eliminado para prevenir problemas de derechos de autor.\n\n🔁 Haz clic en el enlace nuevamente para re-descargar.",
        "auto_delete_warn": "⚠️ <b>Este archivo será auto-eliminado en <u>{time}</u>.</b>\n\n📌 ¡Por favor guárdalo antes de la eliminación!",
        "save_batch": "Guardar en Lote",
        "get_link": "Obtener Enlace",
        "choose_option": "**Elige una opción:**",
        "file_stored": "**Archivo almacenado ✅**\n\nEnlace permanente: {link}",
        "batch_stored": "**Archivos en lote almacenados ✅**\n\nEnlace permanente: {link}",
        "batch_added": "¡Archivo guardado en lote! ({count}/20)\n\nPresiona el botón para obtener el enlace.",
        "batch_limit": "⚠️ **¡Límite de lote alcanzado!**\n\nSolo puedes agregar hasta **20 archivos** por lote.\n\nUsa /clear_batch para empezar un nuevo lote.",
        "get_batch_link": "Obtener Enlace del Lote",
        "open_link": "Abrir Enlace",
        "close_msg": "Cerrar",
        "error_msg": "¡Algo salió mal!\n\n**Error:** `{err}`",
        "token_expired": "⏰ **¡Tu token ha expirado!**",
        "token_verify": "🔐 **Verificación requerida**\n\nHaz clic abajo para verificarte. Token válido por {time}.",
        "verify_button": "✅ Verificar Ahora",
        "token_verified": "✅ **¡Token verificado!**\n\nPuedes acceder archivos por {time}.",
        "clone_success": "✅ **¡Bot clonado!**\n\n@{username} está activo.",
        "clone_usage": "**Uso:** `/clone BOT_TOKEN DB_CHANNEL_ID`",
        "clone_removed": "✅ ¡Bot clonado eliminado!",
        "admin_added": "✅ Usuario `{user_id}` añadido como admin.",
        "admin_removed": "✅ Usuario `{user_id}` eliminado de admin.",
        "admin_list": "📋 **Lista de Admins:**\n\n{admins}",
        "not_admin": "❌ ¡No estás autorizado!",
        "language_changed": "✅ ¡Idioma cambiado a **{lang}**!",
        "choose_lang": "🌐 **Elige tu idioma:**",
        "protect_content_on": "🔒 Protección de contenido **activada**.",
        "stream_link": "🔗 **Enlace de Stream/Descarga:**\n\n{link}",
        "our_channel": "Nuestro Canal",
        "our_group": "Nuestro Grupo",
        "about_bot_btn": "Sobre el Bot",
        "about_dev_btn": "Sobre el Dev",
        "close_btn": "Cerrar 🚪",
        "go_home": "Inicio",
    },

    "fr": {
        "lang_name": "Français 🇫🇷",
        "start_msg": "Bonjour, [{name}](tg://user?id={id})\n\nCeci est un Bot de **Stockage de Fichiers** permanent.\n\n📢 Envoyez-moi n'importe quel fichier et je vous donnerai un lien permanent.",
        "about_bot": "ℹ️ Je suis un bot de stockage de fichiers permanent construit avec Pyrogram.",
        "force_sub": "**Veuillez rejoindre les canaux de mise à jour pour utiliser ce bot!**",
        "join_button": "🤖 Rejoindre le Canal",
        "refresh_button": "🔄 Rafraîchir 🔄",
        "banned_msg": "Désolé, vous êtes banni!",
        "file_deleted": "✅ Le fichier a été auto-supprimé.\n\n🔁 Cliquez à nouveau sur le lien.",
        "auto_delete_warn": "⚠️ <b>Ce fichier sera supprimé dans <u>{time}</u>.</b>",
        "save_batch": "Sauvegarder en Lot",
        "get_link": "Obtenir le Lien",
        "choose_option": "**Choisissez une option:**",
        "file_stored": "**Fichier stocké ✅**\n\nLien permanent: {link}",
        "batch_stored": "**Fichiers en lot stockés ✅**\n\nLien: {link}",
        "batch_added": "Fichier ajouté au lot! ({count}/20)",
        "batch_limit": "⚠️ **Limite de lot atteinte!**\n\nVous ne pouvez ajouter que **20 fichiers** par lot.\n\nUtilisez /clear_batch pour démarrer un nouveau lot.",
        "get_batch_link": "Obtenir le Lien du Lot",
        "open_link": "Ouvrir",
        "close_msg": "Fermer",
        "error_msg": "Erreur!\n\n`{err}`",
        "token_expired": "⏰ **Token expiré!**",
        "token_verify": "🔐 **Vérification requise**\n\nCliquez ci-dessous. Valide pour {time}.",
        "verify_button": "✅ Vérifier",
        "token_verified": "✅ **Vérifié!** Accès pour {time}.",
        "clone_success": "✅ **Bot cloné!** @{username} est actif.",
        "clone_usage": "**Usage:** `/clone BOT_TOKEN DB_CHANNEL_ID`",
        "clone_removed": "✅ Clone supprimé!",
        "admin_added": "✅ `{user_id}` ajouté comme admin.",
        "admin_removed": "✅ `{user_id}` supprimé des admins.",
        "admin_list": "📋 **Admins:**\n\n{admins}",
        "not_admin": "❌ Non autorisé!",
        "language_changed": "✅ Langue changée en **{lang}**!",
        "choose_lang": "🌐 **Choisissez votre langue:**",
        "protect_content_on": "🔒 Protection activée.",
        "stream_link": "🔗 **Lien Stream:**\n\n{link}",
        "our_channel": "Notre Canal",
        "our_group": "Notre Groupe",
        "about_bot_btn": "À Propos",
        "about_dev_btn": "Développeur",
        "close_btn": "Fermer 🚪",
        "go_home": "Accueil",
    },

    "ar": {
        "lang_name": "العربية 🇸🇦",
        "start_msg": "مرحباً، [{name}](tg://user?id={id})\n\nهذا بوت **تخزين ملفات** دائم.\n\n📢 أرسل لي أي ملف وسأعطيك رابط دائم.",
        "about_bot": "ℹ️ أنا بوت تخزين ملفات دائم.",
        "force_sub": "**يرجى الانضمام لقناة التحديثات لاستخدام البوت!**",
        "join_button": "🤖 انضم للقناة",
        "refresh_button": "🔄 تحديث 🔄",
        "banned_msg": "عذراً، أنت محظور!",
        "file_deleted": "✅ تم حذف الملف تلقائياً.\n\n🔁 اضغط الرابط مرة أخرى.",
        "auto_delete_warn": "⚠️ <b>سيتم حذف الملف خلال <u>{time}</u>.</b>",
        "save_batch": "حفظ في دفعة",
        "get_link": "احصل على الرابط",
        "choose_option": "**اختر خياراً:**",
        "file_stored": "**تم تخزين الملف ✅**\n\nالرابط: {link}",
        "batch_stored": "**تم تخزين الدفعة ✅**\n\nالرابط: {link}",
        "batch_added": "تمت الإضافة للدفعة! ({count}/20)",
        "batch_limit": "⚠️ **تم الوصول لحد الدفعة!**\n\nيمكنك إضافة **20 ملفاً** فقط في كل دفعة.\n\nاستخدم /clear_batch لبدء دفعة جديدة.",
        "get_batch_link": "رابط الدفعة",
        "open_link": "فتح",
        "close_msg": "إغلاق",
        "error_msg": "خطأ!\n\n`{err}`",
        "token_expired": "⏰ **انتهت صلاحية التوكن!**",
        "token_verify": "🔐 **التحقق مطلوب**\n\nصالح لمدة {time}.",
        "verify_button": "✅ تحقق الآن",
        "token_verified": "✅ **تم التحقق!** الوصول لمدة {time}.",
        "clone_success": "✅ **تم النسخ!** @{username}",
        "clone_usage": "**الاستخدام:** `/clone BOT_TOKEN DB_CHANNEL_ID`",
        "clone_removed": "✅ تم إزالة النسخة!",
        "admin_added": "✅ تمت إضافة `{user_id}` كمشرف.",
        "admin_removed": "✅ تمت إزالة `{user_id}` من المشرفين.",
        "admin_list": "📋 **المشرفون:**\n\n{admins}",
        "not_admin": "❌ غير مصرح!",
        "language_changed": "✅ تم تغيير اللغة إلى **{lang}**!",
        "choose_lang": "🌐 **اختر لغتك:**",
        "protect_content_on": "🔒 الحماية مفعلة.",
        "stream_link": "🔗 **رابط البث:**\n\n{link}",
        "our_channel": "قناتنا",
        "our_group": "مجموعتنا",
        "about_bot_btn": "عن البوت",
        "about_dev_btn": "المطور",
        "close_btn": "إغلاق 🚪",
        "go_home": "الرئيسية",
    },

    "pt": {
        "lang_name": "Português 🇧🇷",
        "start_msg": "Olá, [{name}](tg://user?id={id})\n\nEste é um Bot de **Armazenamento** permanente.\n\n📢 Envie qualquer arquivo e receba um link permanente.",
        "about_bot": "ℹ️ Bot de armazenamento permanente com Pyrogram.",
        "force_sub": "**Entre nos canais para usar o bot!**",
        "join_button": "🤖 Entrar no Canal",
        "refresh_button": "🔄 Atualizar 🔄",
        "banned_msg": "Desculpe, você está banido!",
        "file_deleted": "✅ Arquivo auto-deletado.\n\n🔁 Clique no link novamente.",
        "auto_delete_warn": "⚠️ <b>Arquivo será deletado em <u>{time}</u>.</b>",
        "save_batch": "Salvar em Lote",
        "get_link": "Obter Link",
        "choose_option": "**Escolha uma opção:**",
        "file_stored": "**Arquivo armazenado ✅**\n\nLink: {link}",
        "batch_stored": "**Lote armazenado ✅**\n\nLink: {link}",
        "batch_added": "Adicionado ao lote! ({count}/20)",
        "batch_limit": "⚠️ **Limite do lote atingido!**\n\nVocê só pode adicionar até **20 arquivos** por lote.\n\nUse /clear_batch para iniciar um novo lote.",
        "get_batch_link": "Link do Lote",
        "open_link": "Abrir",
        "close_msg": "Fechar",
        "error_msg": "Erro!\n\n`{err}`",
        "token_expired": "⏰ **Token expirado!**",
        "token_verify": "🔐 **Verificação necessária**\n\nVálido por {time}.",
        "verify_button": "✅ Verificar",
        "token_verified": "✅ **Verificado!** Acesso por {time}.",
        "clone_success": "✅ **Clonado!** @{username}",
        "clone_usage": "**Uso:** `/clone BOT_TOKEN DB_CHANNEL_ID`",
        "clone_removed": "✅ Clone removido!",
        "admin_added": "✅ `{user_id}` adicionado como admin.",
        "admin_removed": "✅ `{user_id}` removido.",
        "admin_list": "📋 **Admins:**\n\n{admins}",
        "not_admin": "❌ Não autorizado!",
        "language_changed": "✅ Idioma alterado para **{lang}**!",
        "choose_lang": "🌐 **Escolha seu idioma:**",
        "protect_content_on": "🔒 Proteção ativada.",
        "stream_link": "🔗 **Link Stream:**\n\n{link}",
        "our_channel": "Nosso Canal",
        "our_group": "Nosso Grupo",
        "about_bot_btn": "Sobre o Bot",
        "about_dev_btn": "Desenvolvedor",
        "close_btn": "Fechar 🚪",
        "go_home": "Início",
    },

    "id": {
        "lang_name": "Indonesia 🇮🇩",
        "start_msg": "Halo, [{name}](tg://user?id={id})\n\nIni adalah Bot **Penyimpan File** permanen.\n\n📢 Kirim file apapun dan dapatkan link permanen.",
        "about_bot": "ℹ️ Bot penyimpan file permanen dengan Pyrogram.",
        "force_sub": "**Gabung channel update untuk menggunakan bot!**",
        "join_button": "🤖 Gabung Channel",
        "refresh_button": "🔄 Refresh 🔄",
        "banned_msg": "Maaf, Anda diblokir!",
        "file_deleted": "✅ File otomatis dihapus.\n\n🔁 Klik link lagi.",
        "auto_delete_warn": "⚠️ <b>File akan dihapus dalam <u>{time}</u>.</b>",
        "save_batch": "Simpan Batch",
        "get_link": "Dapatkan Link",
        "choose_option": "**Pilih opsi:**",
        "file_stored": "**File tersimpan ✅**\n\nLink: {link}",
        "batch_stored": "**Batch tersimpan ✅**\n\nLink: {link}",
        "batch_added": "Ditambahkan ke batch! ({count}/20)",
        "batch_limit": "⚠️ **Batas batch tercapai!**\n\nAnda hanya bisa menambahkan **20 file** per batch.\n\nGunakan /clear_batch untuk memulai batch baru.",
        "get_batch_link": "Link Batch",
        "open_link": "Buka",
        "close_msg": "Tutup",
        "error_msg": "Error!\n\n`{err}`",
        "token_expired": "⏰ **Token kadaluarsa!**",
        "token_verify": "🔐 **Verifikasi diperlukan**\n\nBerlaku {time}.",
        "verify_button": "✅ Verifikasi",
        "token_verified": "✅ **Terverifikasi!** Akses {time}.",
        "clone_success": "✅ **Dikloning!** @{username}",
        "clone_usage": "**Penggunaan:** `/clone BOT_TOKEN DB_CHANNEL_ID`",
        "clone_removed": "✅ Clone dihapus!",
        "admin_added": "✅ `{user_id}` ditambahkan sebagai admin.",
        "admin_removed": "✅ `{user_id}` dihapus dari admin.",
        "admin_list": "📋 **Admin:**\n\n{admins}",
        "not_admin": "❌ Tidak diizinkan!",
        "language_changed": "✅ Bahasa diubah ke **{lang}**!",
        "choose_lang": "🌐 **Pilih bahasa:**",
        "protect_content_on": "🔒 Proteksi konten aktif.",
        "stream_link": "🔗 **Link Stream:**\n\n{link}",
        "our_channel": "Channel Kami",
        "our_group": "Grup Kami",
        "about_bot_btn": "Tentang Bot",
        "about_dev_btn": "Developer",
        "close_btn": "Tutup 🚪",
        "go_home": "Beranda",
    },

    "tr": {
        "lang_name": "Türkçe 🇹🇷",
        "start_msg": "Merhaba, [{name}](tg://user?id={id})\n\nBu kalıcı bir **Dosya Depolama** Botudur.\n\n📢 Herhangi bir dosya gönderin ve kalıcı link alın.",
        "about_bot": "ℹ️ Pyrogram ile yapılmış kalıcı dosya depolama botu.",
        "force_sub": "**Botu kullanmak için kanala katılın!**",
        "join_button": "🤖 Kanala Katıl",
        "refresh_button": "🔄 Yenile 🔄",
        "banned_msg": "Üzgünüm, yasaklandınız!",
        "file_deleted": "✅ Dosya otomatik silindi.\n\n🔁 Tekrar indirmek için linke tıklayın.",
        "auto_delete_warn": "⚠️ <b>Dosya <u>{time}</u> içinde silinecek.</b>",
        "save_batch": "Toplu Kaydet",
        "get_link": "Link Al",
        "choose_option": "**Bir seçenek seçin:**",
        "file_stored": "**Dosya kaydedildi ✅**\n\nLink: {link}",
        "batch_stored": "**Toplu dosyalar kaydedildi ✅**\n\nLink: {link}",
        "batch_added": "Topluya eklendi! ({count}/20)",
        "batch_limit": "⚠️ **Toplu sınırına ulaşıldı!**\n\nBir topluya en fazla **20 dosya** ekleyebilirsiniz.\n\nYeni bir toplu başlatmak için /clear_batch kullanın.",
        "get_batch_link": "Toplu Link",
        "open_link": "Aç",
        "close_msg": "Kapat",
        "error_msg": "Hata!\n\n`{err}`",
        "token_expired": "⏰ **Token süresi doldu!**",
        "token_verify": "🔐 **Doğrulama gerekli**\n\n{time} geçerli.",
        "verify_button": "✅ Doğrula",
        "token_verified": "✅ **Doğrulandı!** {time} erişim.",
        "clone_success": "✅ **Klonlandı!** @{username}",
        "clone_usage": "**Kullanım:** `/clone BOT_TOKEN DB_CHANNEL_ID`",
        "clone_removed": "✅ Klon kaldırıldı!",
        "admin_added": "✅ `{user_id}` admin olarak eklendi.",
        "admin_removed": "✅ `{user_id}` adminlikten çıkarıldı.",
        "admin_list": "📋 **Adminler:**\n\n{admins}",
        "not_admin": "❌ Yetkisiz!",
        "language_changed": "✅ Dil **{lang}** olarak değiştirildi!",
        "choose_lang": "🌐 **Dilinizi seçin:**",
        "protect_content_on": "🔒 İçerik koruması aktif.",
        "stream_link": "🔗 **Stream Linki:**\n\n{link}",
        "our_channel": "Kanalımız",
        "our_group": "Grubumuz",
        "about_bot_btn": "Bot Hakkında",
        "about_dev_btn": "Geliştirici",
        "close_btn": "Kapat 🚪",
        "go_home": "Ana Sayfa",
    },
}
 
 
def get_text(lang_code: str, key: str) -> str:
    """Get translated text for a given language and key. Falls back to English."""
    lang = LANGUAGES.get(lang_code, LANGUAGES["en"])
    return lang.get(key, LANGUAGES["en"].get(key, key))
 
 
def get_all_lang_codes() -> list:
    """Get all supported language codes."""
    return list(LANGUAGES.keys())
 
 
def get_lang_name(lang_code: str) -> str:
    """Get the display name for a language code."""
    return LANGUAGES.get(lang_code, LANGUAGES["en"]).get("lang_name", lang_code)
 
